### ISSUE TITLE
No Output Generated

### ISSUE THREAD

**Issue by srothmei** [nbbrd/jwsrequests#2]
If i use the tool to process a JDemetra+ Workspace, the standard output is similar to the jwscruncher, but no output data gets stored into the correspdonding folder.
The SAProcessing-files get altered (the timeseries data gets removed).

Using the jwscruncher on the same workspace with the same set of parameters, it produces the output data as expected.

I'm using the JRE 1.8

**Comment by charphi** [comment]
Fixed by f67d66271b888b6f1aaed6c7e051ad9e372e7794
